# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr "Project-Id-Version: profitbricks-python-base 0.5.6\n"
      "Report-Msgid-Bugs-To: frank.brehm@profitbricks.com\n"
      "POT-Creation-Date: 2014-11-02 16:46+0100\n"
      "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
      "Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
      "Language-Team: LANGUAGE <LL@li.org>\n"
      "Language: \n"
      "MIME-Version: 1.0\n"
      "Content-Type: text/plain; charset=UTF-8\n"
      "Content-Transfer-Encoding: 8bit\n"
      "Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"

#: argparse.py:800
msgid ".__call__() not defined"
msgstr ""

#: argparse.py:1084
#, python-format
msgid "unknown parser %r (choices: %s)"
msgstr ""

#: argparse.py:1125
#, python-format
msgid "argument \"-\" with mode %r"
msgstr ""

#: argparse.py:1132
#, python-format
msgid "can't open '%s': %s"
msgstr ""

#: argparse.py:1336
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr ""

#: argparse.py:1374
msgid "'required' is an invalid argument for positionals"
msgstr ""

#: argparse.py:1395
#, python-format
msgid "invalid option string %r: must start with a character %r"
msgstr ""

#: argparse.py:1415
#, python-format
msgid "dest= is required for options like %r"
msgstr ""

#: argparse.py:1432
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr ""

#: argparse.py:1450
#, python-format
msgid "conflicting option string(s): %s"
msgstr ""

#: argparse.py:1514
msgid "mutually exclusive arguments must be optional"
msgstr ""

#: argparse.py:1584
msgid "positional arguments"
msgstr ""

#: argparse.py:1585
msgid "optional arguments"
msgstr ""

#: argparse.py:1600
msgid "show this help message and exit"
msgstr ""

#: argparse.py:1606
msgid "show program's version number and exit"
msgstr ""

#: argparse.py:1638
msgid "cannot have multiple subparser arguments"
msgstr ""

#: argparse.py:1690
#, python-format
msgid "unrecognized arguments: %s"
msgstr ""

#: argparse.py:1787
#, python-format
msgid "not allowed with argument %s"
msgstr ""

#: argparse.py:1833 argparse.py:1847
#, python-format
msgid "ignored explicit argument %r"
msgstr ""

#: argparse.py:1937
msgid "too few arguments"
msgstr ""

#: argparse.py:1944
#, python-format
msgid "argument %s is required"
msgstr ""

#: argparse.py:1958
#, python-format
msgid "one of the arguments %s is required"
msgstr ""

#: argparse.py:2004
msgid "expected one argument"
msgstr ""

#: argparse.py:2005
msgid "expected at most one argument"
msgstr ""

#: argparse.py:2006
msgid "expected at least one argument"
msgstr ""

#: argparse.py:2065
#, python-format
msgid "ambiguous option: %s could match %s"
msgstr ""

#: argparse.py:2127
#, python-format
msgid "unexpected option string: %s"
msgstr ""

#: argparse.py:2228
#, python-format
msgid "%r is not callable"
msgstr ""

#: argparse.py:2244
#, python-format
msgid "invalid %s value: %r"
msgstr ""

#: argparse.py:2254
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr ""

#: argparse.py:2347
#, python-format
msgid "%s: error: %s\n"
msgstr ""

#: bin/crc64:49
msgid "Crc64-Application object:"
msgstr ""

#: pb_base/app.py:89 pb_base/app.py:92
#, python-format
msgid "Faked exit to OS. Exit value: %(rv)d, message: %(msg)r"
msgstr ""

#: pb_base/app.py:309 pb_base/app.py:313
msgid "usage: "
msgstr ""

#: pb_base/app.py:475 pb_base/app.py:479
msgid "executing pre_run() ..."
msgstr ""

#: pb_base/app.py:513 pb_base/app.py:516
msgid "The application is not complete initialized."
msgstr ""

#: pb_base/app.py:524 pb_base/app.py:527
#, python-format
msgid "Object '%s' seems not to be completely initialized."
msgstr ""

#: pb_base/app.py:534 pb_base/app.py:537 pb_base/fork_daemon.py:366
msgid "Ending."
msgstr ""

#: pb_base/app.py:553 pb_base/app.py:556
msgid "executing post_run() ..."
msgstr ""

#: pb_base/app.py:575 pb_base/app.py:578 pb_base/crc64_app.py:72
msgid "General options"
msgstr ""

#: pb_base/app.py:584 pb_base/app.py:587
msgid "Use colored output for messages."
msgstr ""

#: pb_base/app.py:590 pb_base/app.py:593
msgid "Increase the verbosity level"
msgstr ""

#: pb_base/app.py:596 pb_base/app.py:599
msgid "Show this help message and exit"
msgstr ""

#: pb_base/app.py:602 pb_base/app.py:605
msgid "Display brief usage message and exit"
msgstr ""

#: pb_base/app.py:607 pb_base/app.py:610
#, python-format
msgid "Version of %%(prog)s: %s"
msgstr ""

#: pb_base/app.py:608 pb_base/app.py:611
msgid "Show program's version number and exit"
msgstr ""

#: pb_base/cfg_app.py:308 pb_base/cfg_app.py:319
msgid "Configuration file to use additional to the standard configuration files."
msgstr ""

#: pb_base/cfg_app.py:316 pb_base/cfg_app.py:327
msgid "The encoding character set of the configuration files."
msgstr ""

#: pb_base/cfg_app.py:324 pb_base/cfg_app.py:335
msgid "Generates a default configuration, prints it out to STDOUT and exit."
msgstr ""

#: pb_base/cfg_app.py:427 pb_base/cfg_app.py:437
#, python-format
msgid "Read cfg files with character set '%s' ..."
msgstr ""

#: pb_base/cfg_app.py:434 pb_base/cfg_app.py:443
msgid "Used config specification:"
msgstr ""

#: pb_base/cfg_app.py:454 pb_base/cfg_app.py:464
#, python-format
msgid "Reading in configuration file '%s' ..."
msgstr ""

#: pb_base/cfg_app.py:465 pb_base/cfg_app.py:475 pb_base/cfg_app.py:480
#: pb_base/cfg_app.py:484 pb_base/cfg_app.py:490
#, python-format
msgid "Wrong configuration in %r found:"
msgstr ""

#: pb_base/cfg_app.py:467 pb_base/cfg_app.py:477 pb_base/cfg_app.py:482
#: pb_base/cfg_app.py:486 pb_base/cfg_app.py:492
msgid "Configuration error"
msgstr ""

#: pb_base/cfg_app.py:471 pb_base/cfg_app.py:475 pb_base/cfg_app.py:481
msgid "Found configuration:"
msgstr ""

#: pb_base/cfg_app.py:476 pb_base/cfg_app.py:480 pb_base/cfg_app.py:486
msgid "Validation result:"
msgstr ""

#: pb_base/cfg_app.py:493 pb_base/cfg_app.py:496 pb_base/cfg_app.py:502
msgid "Using merged configuration:"
msgstr ""

#: pb_base/cfg_app.py:495 pb_base/cfg_app.py:499 pb_base/cfg_app.py:505
msgid "Using configuration:"
msgstr ""

#: pb_base/cfg_app.py:516 pb_base/cfg_app.py:519 pb_base/cfg_app.py:525
#: pb_base/handler/df.py:463 pb_base/handler/fuser.py:207
msgid "Undefined error"
msgstr ""

#: pb_base/cfg_app.py:538 pb_base/cfg_app.py:540 pb_base/cfg_app.py:546
#, python-format
msgid "In section %(section)s key '%(key)s': %(value)s"
msgstr ""

#: pb_base/crc64_app.py:77
msgid "Generates a 64 bit checksum for all given positional arguments."
msgstr ""

#: pb_base/crc64_app.py:111
msgid "The token to generate a CRC64 digest from."
msgstr ""

#: pb_base/daemon.py:163 pb_base/daemon.py:175 pb_base/daemon.py:176
#, python-format
msgid "Invalid facility name '%s' given."
msgstr ""

#: pb_base/daemon.py:401 pb_base/daemon.py:414 pb_base/daemon.py:415
#, python-format
msgid "The syslog facility to use when logging as a daemon (default: %s)."
msgstr ""

#: pb_base/daemon.py:412
msgid "Log to console instead to syslog."
msgstr ""

#: pb_base/daemon.py:413
msgid "Don't daemonize the application, running in foreground."
msgstr ""

#: pb_base/daemon.py:521 pb_base/daemon.py:532 pb_base/daemon.py:533
#, python-format
msgid "Got a signal %s."
msgstr ""

#: pb_base/daemon.py:524 pb_base/daemon.py:534 pb_base/daemon.py:535
#, python-format
msgid "Process with PID %(pid)d got signal %(signal)s."
msgstr ""

#: pb_base/daemon.py:529 pb_base/daemon.py:539 pb_base/daemon.py:540
msgid "Nothing to do on signal USR1 or USR2."
msgstr ""

#: pb_base/daemon.py:537 pb_base/daemon.py:547 pb_base/daemon.py:548
msgid "Got a signal for forced shutdown."
msgstr ""

#: pb_base/daemon.py:559 pb_base/daemon.py:569 pb_base/daemon.py:570
#, python-format
msgid "Exit from %s, so sad ..."
msgstr ""

#: pb_base/daemon.py:576 pb_base/daemon.py:586 pb_base/daemon.py:587
#, python-format
msgid "Using '%s' as error log file."
msgstr ""

#: pb_base/daemon.py:580 pb_base/daemon.py:589 pb_base/daemon.py:590
#, python-format
msgid "Using '%s' as parent directory of error log file."
msgstr ""

#: pb_base/daemon.py:584 pb_base/daemon.py:593 pb_base/daemon.py:594
#, python-format
msgid "Log directory '%s' doesn't exists."
msgstr ""

#: pb_base/daemon.py:589 pb_base/daemon.py:597 pb_base/daemon.py:598
#, python-format
msgid "Log directory '%s' exists, but is not a directory."
msgstr ""

#: pb_base/daemon.py:597 pb_base/daemon.py:605 pb_base/daemon.py:606
#, python-format
msgid "Could not open error logfile: %s"
msgstr ""

#: pb_base/daemon.py:602 pb_base/daemon.py:609 pb_base/daemon.py:610
#, python-format
msgid "Could not open error logfile %(log)s: %(err)s"
msgstr ""

#. do the first fork
#: pb_base/daemon.py:608 pb_base/daemon.py:615 pb_base/daemon.py:616
msgid "First fork ..."
msgstr ""

#: pb_base/daemon.py:615 pb_base/daemon.py:622 pb_base/daemon.py:623
msgid "Fork #1 failed: "
msgstr ""

#. do second fork
#: pb_base/daemon.py:624 pb_base/daemon.py:631 pb_base/daemon.py:632
msgid "Second fork ..."
msgstr ""

#: pb_base/daemon.py:631 pb_base/daemon.py:638 pb_base/daemon.py:639
msgid "Fork #2 failed: "
msgstr ""

#: pb_base/daemon.py:635 pb_base/daemon.py:641 pb_base/daemon.py:642
#, python-format
msgid "%(app)s (v%(ver)s) started as daemon with PID %(pid)d."
msgstr ""

#. redirect standard file descriptors
#: pb_base/daemon.py:641 pb_base/daemon.py:647 pb_base/daemon.py:648
msgid "Redirect standard file descriptors ..."
msgstr ""

#: pb_base/daemon.py:653 pb_base/daemon.py:659 pb_base/daemon.py:660
msgid "I'm a daemon now - Boooaaaahhh!!!"
msgstr ""

#: pb_base/errors.py:66 pb_base/errors.py:68
#, python-format
msgid "Function %(func)s() has to be overridden in class '%(cls)s'."
msgstr ""

#: pb_base/errors.py:91 pb_base/errors.py:96
#, python-format
msgid "Given positional arguments: %r."
msgstr ""

#: pb_base/errors.py:92 pb_base/errors.py:97
#, python-format
msgid "Given keyword arguments: %r."
msgstr ""

#: pb_base/errors.py:92
#, python-format
msgid "Invalid call to method %(m)s() in a object of class %(c)r."
msgstr ""

#: pb_base/errors.py:93
msgid "(probably not overridden?)."
msgstr ""

#: pb_base/errors.py:124 pb_base/errors.py:130
#, python-format
msgid " (timeout after %0.1f secs)"
msgstr ""

#: pb_base/errors.py:150 pb_base/errors.py:157
msgid "Timeout error on reading"
msgstr ""

#: pb_base/errors.py:171 pb_base/errors.py:179
msgid "Timeout error on writing"
msgstr ""

#: pb_base/errors.py:202 pb_base/errors.py:212
#, python-format
msgid "Couldn't occupy lockfile %(file)r in %(secs)0.1f seconds with %(tries)d "
      "tries."
msgstr ""

#: pb_base/fork_daemon.py:257
#, python-format
msgid "Wrong value for max_children %(val)d, must be between 1 and %(max)d."
msgstr ""

#: pb_base/fork_daemon.py:278
#, python-format
msgid "Wrong value for timeout_collect_children %d, must be greater than zero."
msgstr ""

#: pb_base/fork_daemon.py:359
msgid "Cleaning up ..."
msgstr ""

#: pb_base/fork_daemon.py:369
#, python-format
msgid "Daemon (v%s) ended."
msgstr ""

#: pb_base/fork_daemon.py:396
msgid "Collecting all child processes ..."
msgstr ""

#: pb_base/fork_daemon.py:399
msgid "Collecting finished child processes ..."
msgstr ""

#: pb_base/fork_daemon.py:403
msgid "No active children found."
msgstr ""

#: pb_base/fork_daemon.py:435
#, python-format
msgid "Sending signal %d to all child processes."
msgstr ""

#: pb_base/fork_daemon.py:445
#, python-format
msgid "Maximum timeout of %d seconds for waiting on finished child processes "
      "reached."
msgstr ""

#: pb_base/fork_daemon.py:449
#, python-format
msgid "New stage %d in waiting for child processes."
msgstr ""

#: pb_base/fork_daemon.py:452
#, python-format
msgid "Waiting for finished children, stage %d."
msgstr ""

#: pb_base/fork_daemon.py:500
#, python-format
msgid "Removing child %d from active child list ..."
msgstr ""

#: pb_base/fork_daemon.py:523
msgid "Forking a child process ..."
msgstr ""

#: pb_base/fork_daemon.py:541
#, python-format
msgid "Forked with process ID %d."
msgstr ""

#: pb_base/fork_daemon.py:548
msgid "And here is the child ..."
msgstr ""

#: pb_base/handler/__init__.py:78
msgid "Unknown OS command."
msgstr ""

#: pb_base/handler/__init__.py:85
msgid "Empty command list given."
msgstr ""

#: pb_base/handler/__init__.py:94
msgid "Could not found OS command"
msgid_plural    "Could not found OS commands"
msgstr[0]       ""
msgstr[1]       ""

#: pb_base/handler/__init__.py:331
#, python-format
msgid "Searching for command '%s' ..."
msgstr ""

#: pb_base/handler/__init__.py:336
#, python-format
msgid "Command '%s' doesn't exists."
msgstr ""

#: pb_base/handler/__init__.py:339 pb_base/handler/__init__.py:355
#, python-format
msgid "Command '%s' is not executable."
msgstr ""

#: pb_base/handler/__init__.py:360 pb_base/handler/__init__.py:362
#, python-format
msgid "Command '%s' not found."
msgstr ""

#: pb_base/handler/__init__.py:443
#, python-format
msgid "Executing %r"
msgstr ""

#: pb_base/handler/__init__.py:446
msgid "Quiet execution"
msgstr ""

#: pb_base/handler/__init__.py:485 pb_base/handler/__init__.py:501
#, python-format
msgid "Decoding %(what)s from %(enc)r."
msgstr ""

#: pb_base/handler/__init__.py:491 pb_base/handler/__init__.py:517
#, python-format
msgid "Output on %(where)s: %(what)r."
msgstr ""

#: pb_base/handler/__init__.py:523
#, python-format
msgid "Returncode: %s"
msgstr ""

#: pb_base/handler/__init__.py:567 pb_base/handler/__init__.py:637
msgid "File doesn't exists."
msgstr ""

#: pb_base/handler/__init__.py:569
msgid "Read permission denied."
msgstr ""

#: pb_base/handler/__init__.py:572
#, python-format
msgid "Reading file content of %r ..."
msgstr ""

#: pb_base/handler/__init__.py:642 pb_base/handler/__init__.py:650
#, python-format
msgid "Write permission to %r denied."
msgstr ""

#: pb_base/handler/__init__.py:645 pb_base/handler/__init__.py:653
msgid "Write permission denied."
msgstr ""

#: pb_base/handler/__init__.py:657
#, python-format
msgid "Write %(what)r into %(to)r."
msgstr ""

#: pb_base/handler/__init__.py:660
#, python-format
msgid "Writing %r ..."
msgstr ""

#: pb_base/handler/__init__.py:664
#, python-format
msgid "Simulating write into %r."
msgstr ""

#: pb_base/handler/__init__.py:672
#, python-format
msgid "Opening '%s' for write unbuffered ..."
msgstr ""

#: pb_base/handler/__init__.py:679
#, python-format
msgid "Closing '%s' ..."
msgstr ""

#: pb_base/handler/__init__.py:712
#, python-format
msgid "Dumping data from %(src)r to %(tgt)r ..."
msgstr ""

#: pb_base/handler/__init__.py:729
#, python-format
msgid "Opening %r for read."
msgstr ""

#: pb_base/handler/__init__.py:733
#, python-format
msgid "Error opening source %(src)r: %(msg)s"
msgstr ""

#: pb_base/handler/__init__.py:738 pb_base/handler/__init__.py:829
#, python-format
msgid "Opening %r for write"
msgstr ""

#: pb_base/handler/__init__.py:743
#, python-format
msgid "Error opening target %(tgt)r: %(msg)s"
msgstr ""

#: pb_base/handler/__init__.py:748 pb_base/handler/__init__.py:838
#, python-format
msgid "Copying (buffer size %d Bytes)..."
msgstr ""

#: pb_base/handler/__init__.py:754
#, python-format
msgid "Seeking %(bytes)d Bytes (%(human)s) in input to %(src)r."
msgstr ""

#: pb_base/handler/__init__.py:759 pb_base/handler/__init__.py:844
#, python-format
msgid "Seeking %(bytes)d Bytes (%(human)s) in output to %(tgt)r."
msgstr ""

#: pb_base/handler/__init__.py:773 pb_base/handler/__init__.py:858
#, python-format
msgid "No space left on output device %r."
msgstr ""

#: pb_base/handler/__init__.py:777
#, python-format
msgid "Error copying source %(src)r to target %(tgt)r: %(msg)s"
msgstr ""

#: pb_base/handler/__init__.py:785 pb_base/handler/__init__.py:869
#, python-format
msgid "%(bytes)d Bytes (%(human)s) written to output device %(tgt)r."
msgstr ""

#: pb_base/handler/__init__.py:815
#, python-format
msgid "Dumping binary zeroes to %r ..."
msgstr ""

#: pb_base/handler/__init__.py:833
#, python-format
msgid "%(errname)s opening target %(tgt)r: %(msg)s"
msgstr ""

#: pb_base/handler/__init__.py:862
#, python-format
msgid "Error dumping binary zeroes to target %(tgt)r: %(msg)s"
msgstr ""

#: pb_base/handler/df.py:334 pb_base/handler/fuser.py:136
msgid "Initialized."
msgstr ""

#: pb_base/handler/df.py:410
#, python-format
msgid "Checking existence of %r ..."
msgstr ""

#: pb_base/handler/df.py:412
#, python-format
msgid "Filesystem object %r doesn't exists."
msgstr ""

#: pb_base/handler/df.py:416
#, python-format
msgid "%r is not given as an absolute path."
msgstr ""

#: pb_base/handler/df.py:421
#, python-format
msgid "Calling 'df' for the following objects:"
msgstr ""

#: pb_base/handler/df.py:425
msgid "Calling 'df' for real all filesystems."
msgstr ""

#: pb_base/handler/df.py:427
msgid "Calling 'df' for local filesystems."
msgstr ""

#: pb_base/handler/df.py:429
msgid "Calling 'df' for all filesystems."
msgstr ""

#: pb_base/handler/df.py:468
#, python-format
msgid "Error %(nr)d on getting free space of %(obj)r: %(err)s"
msgstr ""

#: pb_base/handler/df.py:474
#, python-format
msgid "Didn't found any usable information in output of %r:"
msgstr ""

#: pb_base/handler/df.py:486
#, python-format
msgid "Could not evaluate line %(line)r in output of command %(cmd)r."
msgstr ""

#: pb_base/handler/fuser.py:184
#, python-format
msgid "Filesystem object %r doesn't seems to exist. Continue because of the "
      "'force' flag."
msgstr ""

#: pb_base/handler/fuser.py:186
#, python-format
msgid "Filesystem object %r doesn't seems to exist."
msgstr ""

#: pb_base/handler/fuser.py:203
#, python-format
msgid "%r will not be used by some other processes."
msgstr ""

#: pb_base/handler/fuser.py:212
#, python-format
msgid "Error %(nr)d on getting fuser information of %(obj)r: %(err)s"
msgstr ""

#: pb_base/handler/fuser.py:226
#, python-format
msgid "%r is not an integer value usable as PID."
msgstr ""

#: pb_base/handler/lock.py:98
#, python-format
msgid "Locking directory %r doesn't exists or is not a directory."
msgstr ""

#: pb_base/handler/lock.py:124 pb_base/handler/lock.py:754
#, python-format
msgid "Locking directory %r isn't writeable."
msgstr ""

#: pb_base/handler/lock.py:194
msgid "No lockfile given on init of a PbLock object."
msgstr ""

#: pb_base/handler/lock.py:198 pb_base/handler/lock.py:970
#, python-format
msgid "Lockfile %r doesn't exists."
msgstr ""

#: pb_base/handler/lock.py:203
#, python-format
msgid "Lockfile %r is not a regular file."
msgstr ""

#: pb_base/handler/lock.py:328
#, python-format
msgid "Automatic removing of %r ..."
msgstr ""

#: pb_base/handler/lock.py:349
#, python-format
msgid "Refreshing atime and mtime of %r to the current timestamp."
msgstr ""

#: pb_base/handler/lock.py:496 pb_base/handler/lock.py:518
#: pb_base/handler/lock.py:540 pb_base/handler/lock.py:563
#: pb_base/handler/lock.py:681 pb_base/handler/lock.py:693
#: pb_base/handler/lock.py:705 pb_base/handler/lock.py:723
#: pb_base/handler/lock.py:958
#, python-format
msgid "Value %(val)r for %(what)s is not a Number."
msgstr ""

#: pb_base/handler/lock.py:501 pb_base/handler/lock.py:545
#: pb_base/handler/lock.py:568 pb_base/handler/lock.py:685
#: pb_base/handler/lock.py:709 pb_base/handler/lock.py:727
#: pb_base/handler/lock.py:962
#, python-format
msgid "The value for %(what)s must be greater than zero (is %(val)r)."
msgstr ""

#: pb_base/handler/lock.py:523 pb_base/handler/lock.py:697
#, python-format
msgid "The value for %(what)s must be greater than or equal to zero (is %(val)r)."
msgstr ""

#: pb_base/handler/lock.py:736
#, python-format
msgid "Invalid PID %d given on calling create_lockfile()."
msgstr ""

#: pb_base/handler/lock.py:746
#, python-format
msgid "Trying to lock lockfile %r ..."
msgstr ""

#: pb_base/handler/lock.py:748
#, python-format
msgid "Using lock directory %r ..."
msgstr ""

#: pb_base/handler/lock.py:777
#, python-format
msgid "Current time difference: %0.3f seconds."
msgstr ""

#. Try creating lockfile exclusive
#: pb_base/handler/lock.py:782
#, python-format
msgid "Try %(try_nr)d on creating lockfile %(lfile)r ..."
msgstr ""

#: pb_base/handler/lock.py:794 pb_base/handler/lock.py:905
#, python-format
msgid "Removing lockfile %r ..."
msgstr ""

#: pb_base/handler/lock.py:799 pb_base/handler/lock.py:913
#, python-format
msgid "Error on removing lockfile %(lfile)r: %(err)s"
msgstr ""

#: pb_base/handler/lock.py:812
#, python-format
msgid "Sleeping for %0.1f seconds."
msgstr ""

#. or an int for success
#: pb_base/handler/lock.py:827
#, python-format
msgid "Got a lock for lockfile %r."
msgstr ""

#: pb_base/handler/lock.py:831
#, python-format
msgid "Write %(what)r in lockfile %(lfile)r ..."
msgstr ""

#: pb_base/handler/lock.py:865
#, python-format
msgid "Trying to open %r exclusive ..."
msgstr ""

#: pb_base/handler/lock.py:867
msgid "Simulation mode, no real creation of a lockfile."
msgstr ""

#: pb_base/handler/lock.py:873
#, python-format
msgid "Error on creating lockfile %(lfile)r: %(err)s"
msgstr ""

#: pb_base/handler/lock.py:902
#, python-format
msgid "Lockfile %r to remove doesn't exists."
msgstr ""

#: pb_base/handler/lock.py:907
msgid "Simulation mode - lockfile won't removed."
msgstr ""

#: pb_base/handler/lock.py:917
msgid "Stacktrace"
msgstr ""

#: pb_base/handler/lock.py:966
#, python-format
msgid "Checking lockfile %r ..."
msgstr ""

#: pb_base/handler/lock.py:974
#, python-format
msgid "No read access for lockfile %r."
msgstr ""

#: pb_base/handler/lock.py:978
#, python-format
msgid "No write access for lockfile %r."
msgstr ""

#: pb_base/handler/lock.py:984
#, python-format
msgid "Unusable lockfile %r."
msgstr ""

#: pb_base/handler/lock.py:987
#, python-format
msgid "Process with PID %d is unfortunately dead."
msgstr ""

#: pb_base/handler/lock.py:990
#, python-format
msgid "Process with PID %d is even running."
msgstr ""

#: pb_base/handler/lock.py:1004
#, python-format
msgid "Lockfile %(lfile)r is older than %(max)d seconds (%(age)d seconds)."
msgstr ""

#: pb_base/handler/lock.py:1007
#, python-format
msgid "Lockfile %(lfile)r is %(age)d seconds old, but not old enough (%(max)d "
      "seconds)."
msgstr ""

#: pb_base/handler/lock.py:1030
#, python-format
msgid "Trying to open pidfile %r ..."
msgstr ""

#: pb_base/handler/lock.py:1034
#, python-format
msgid "Could not open pidfile %r for reading:"
msgstr ""

#: pb_base/handler/lock.py:1047
#, python-format
msgid "First line of pidfile %r was empty."
msgstr ""

#: pb_base/handler/lock.py:1054 pb_base/handler/lock.py:1063
#: pb_base/handler/lock.py:1064 pb_base/handler/lock.py:1068
#: pb_base/handler/lock.py:1072
#, python-format
msgid "Invalid PID %(pid)d in %(file)r found."
msgstr ""

#: pb_base/handler/lock.py:1058
#, python-format
msgid "Could not interprete %(cont)r as a PID from %(file)r:"
msgstr ""

#: pb_base/pidfile.py:75
#, python-format
msgid "Invalid pidfile '%(pidfile)s' given: %(reason)s"
msgstr ""

#: pb_base/pidfile.py:78
#, python-format
msgid "Invalid pidfile %r given."
msgstr ""

#: pb_base/pidfile.py:107
#, python-format
msgid "The pidfile '%(pidfile)s is currently in use by the application with the "
      "PID %(pid)d."
msgstr ""

#: pb_base/pidfile.py:181
msgid "No filename given on initializing PidFile object."
msgstr ""

#: pb_base/pidfile.py:298
#, python-format
msgid "Pidfile '%s' doesn't exists, not removing."
msgstr ""

#: pb_base/pidfile.py:304
#, python-format
msgid "Auto removing disabled, don't deleting '%s'."
msgstr ""

#: pb_base/pidfile.py:309
#, python-format
msgid "Removing pidfile '%s' ..."
msgstr ""

#: pb_base/pidfile.py:312 pb_base/pidfile.py:347
msgid "Just kidding .."
msgstr ""

#: pb_base/pidfile.py:317
#, python-format
msgid "Could not delete pidfile %(file)r: %(err)s"
msgstr ""

#: pb_base/pidfile.py:337 pb_base/pidfile.py:404
#, python-format
msgid "Invalid PID %(pid)d for creating pidfile %(pidfile)r given."
msgstr ""

#: pb_base/pidfile.py:345
#, python-format
msgid "Deleting pidfile '%s' ..."
msgstr ""

#: pb_base/pidfile.py:355
#, python-format
msgid "Trying opening '%s' exclusive ..."
msgstr ""

#: pb_base/pidfile.py:358 pb_base/pidfile.py:414
#, python-format
msgid "Simulation mode - don't real writing in '%s'."
msgstr ""

#: pb_base/pidfile.py:368
#, python-format
msgid "Error on creating pidfile '%(pidfile)s': %(err)s"
msgstr ""

#: pb_base/pidfile.py:373 pb_base/pidfile.py:427
#, python-format
msgid "Writing %(pid)d into '%(pidfile)s' ..."
msgstr ""

#: pb_base/pidfile.py:398
msgid "Calling recreate() on a not self created pidfile."
msgstr ""

#: pb_base/pidfile.py:411
#, python-format
msgid "Trying opening '%s' for recreate ..."
msgstr ""

#: pb_base/pidfile.py:422
#, python-format
msgid "Error on recreating pidfile '%(pidfile)s': %(err)s"
msgstr ""

#: pb_base/pidfile.py:458
#, python-format
msgid "Pidfile parent directory '%s' doesn't exists."
msgstr ""

#: pb_base/pidfile.py:462
#, python-format
msgid "Pidfile parent directory '%s' is not a directory."
msgstr ""

#: pb_base/pidfile.py:466
#, python-format
msgid "No write access to pidfile parent directory '%s'."
msgstr ""

#: pb_base/pidfile.py:473
msgid "It is not a regular file."
msgstr ""

#: pb_base/pidfile.py:490
#, python-format
msgid "Reading content of pidfile %r ..."
msgstr ""

#: pb_base/pidfile.py:515
#, python-format
msgid "No useful information found in pidfile %(file)r: %(line)r"
msgstr ""

#: pb_base/pidfile.py:520
#, python-format
msgid "Trying check for process with PID %d ..."
msgstr ""

#: pb_base/pidfile.py:527
#, python-format
msgid "Process with PID %d anonymous died."
msgstr ""

#: pb_base/pidfile.py:530
#, python-format
msgid "No permission to signal the process %d ..."
msgstr ""

#: pb_base/pidfile.py:533
#, python-format
msgid "Unknown error: %r."
msgstr ""

#: pb_base/pidfile_app.py:198 pb_base/pidfile_app.py:199
#, python-format
msgid "Using pidfile: %r."
msgstr ""

#: pb_base/pidfile_app.py:203 pb_base/pidfile_app.py:354
msgid "Initialising PidFile object ..."
msgstr ""

#: pb_base/pidfile_app.py:282 pb_base/pidfile_app.py:294
#, python-format
msgid "Setting pidfile to %r by configuration."
msgstr ""

#: pb_base/pidfile_app.py:298 pb_base/pidfile_app.py:310
#, python-format
msgid "The name of the pidfile (Default: %s)."
msgstr ""

#: pb_base/pidfile_app.py:313 pb_base/pidfile_app.py:325
msgid "Simulation mode, nothing is really done."
msgstr ""

#: pb_base/pidfile_app.py:331 pb_base/pidfile_app.py:343
#, python-format
msgid "Setting pidfile to %r by commandline parameter."
msgstr ""

#: pb_base/pidfile_app.py:366 pb_base/pidfile_app.py:383
#, python-format
msgid "Creating pidfile %r ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:79
msgid "Timeout error on reading from socket"
msgstr ""

#: pb_base/socket_obj/__init__.py:98
msgid "Timeout error on writing to socket"
msgstr ""

#: pb_base/socket_obj/__init__.py:170
#, python-format
msgid "Invalid request_queue_size %r, must be between 0 and 5."
msgstr ""

#: pb_base/socket_obj/__init__.py:180
#, python-format
msgid "Invalid buffer size %(bs)r, must be between %(min)d and %(max)d."
msgstr ""

#: pb_base/socket_obj/__init__.py:338
msgid "Closing socket ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:357
msgid "Resetting socket connection ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:376
msgid "Cannot send message to the receipient, because the socket connection is "
      "interrupted."
msgstr ""

#: pb_base/socket_obj/__init__.py:386
msgid "Cannot send message to the receipient, because the socket connection is "
      "closed."
msgstr ""

#: pb_base/socket_obj/__init__.py:390
#, python-format
msgid "Sending %r to socket."
msgstr ""

#: pb_base/socket_obj/__init__.py:405
msgid "Cannot accept connection, socket is not bonded."
msgstr ""

#: pb_base/socket_obj/__init__.py:413
#, python-format
msgid "Got a request from '%s'."
msgstr ""

#: pb_base/socket_obj/__init__.py:415
msgid "Got a request from somewhere from system."
msgstr ""

#: pb_base/socket_obj/__init__.py:436
msgid "Trying to get data ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:445
#, python-format
msgid "Got data: %r."
msgstr ""

#: pb_base/socket_obj/__init__.py:450
msgid "Got EOF, counterpart has interrupted ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:501
msgid "Performing input buffer ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:505
#, python-format
msgid "Current input buffer: %r"
msgstr ""

#: pb_base/socket_obj/__init__.py:511
#, python-format
msgid "Got a line: %r"
msgstr ""

#: pb_base/socket_obj/__init__.py:512
#, python-format
msgid "Current input buffer after read_line(): %r"
msgstr ""

#: pb_base/socket_obj/tcp.py:50
#, python-format
msgid "The TCP port number must be a positive integer value, not %d."
msgstr ""

#: pb_base/socket_obj/tcp.py:180
#, python-format
msgid "The IP address family must be one of %(a1)r, %(a2)r or %(a3)r."
msgstr ""

#: pb_base/socket_obj/tcp.py:312
msgid "Cannot connect to an undefined IP address."
msgstr ""

#: pb_base/socket_obj/tcp.py:316
#, python-format
msgid "Connecting to TCP address %(addr)r, port %(port)d ..."
msgstr ""

#: pb_base/socket_obj/tcp.py:320
#, python-format
msgid "The socket is already connected to %(addr)r, port %(port)d ..."
msgstr ""

#: pb_base/socket_obj/tcp.py:325
#, python-format
msgid "The application is allready bonded to %(addr)r, port %(port)d ..."
msgstr ""

#: pb_base/socket_obj/tcp.py:351 pb_base/socket_obj/tcp.py:431
#, python-format
msgid "TCP %s results:"
msgstr ""

#: pb_base/socket_obj/tcp.py:375
#, python-format
msgid "Could not open socket to %(addr)r, port %(port)d."
msgstr ""

#: pb_base/socket_obj/tcp.py:398
#, python-format
msgid "Creating a listening TCP socket on address %(addr)r, port %(port)d ..."
msgstr ""

#: pb_base/socket_obj/tcp.py:402
#, python-format
msgid "The socket is already connected to address %(addr)r, port %(port)d..."
msgstr ""

#: pb_base/socket_obj/tcp.py:406
#, python-format
msgid "The application is already bonded to address %(addr)r, port %(port)d..."
msgstr ""

#: pb_base/socket_obj/tcp.py:462
#, python-format
msgid "Could not open listening TCP socket on %(addr)r, port %(port)d."
msgstr ""

#: pb_base/socket_obj/tcp.py:475
#, python-format
msgid "Binding TCP socket to server address: %s"
msgstr ""

#: pb_base/socket_obj/unix.py:65
#, python-format
msgid "The Unix socket file %r was not found."
msgstr ""

#: pb_base/socket_obj/unix.py:76
#, python-format
msgid "Invalid permissions to connect to Unix socket %r."
msgstr ""

#: pb_base/socket_obj/unix.py:256
#, python-format
msgid "Removing socket file %r ..."
msgstr ""

#: pb_base/socket_obj/unix.py:266
#, python-format
msgid "Connecting to Unix Domain Socket '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:270 pb_base/socket_obj/unix.py:301
#, python-format
msgid "The socket is already connected to '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:274 pb_base/socket_obj/unix.py:305
#, python-format
msgid "The application is already bonded to '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:285
#, python-format
msgid "Error connecting to Unix Socket '%(sock)s': %(err)s"
msgstr ""

#: pb_base/socket_obj/unix.py:297
#, python-format
msgid "Creating and binding to Unix Domain Socket '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:325
#, python-format
msgid "Setting permissions of '%(sock)s' to 0%(perm)o."
msgstr ""

#: pb_base/socket_obj/unix.py:338
#, python-format
msgid "Invalid owner name '%s' for socket creation given."
msgstr ""

#: pb_base/socket_obj/unix.py:350
#, python-format
msgid "Invalid group name '%s' for socket creation given."
msgstr ""

#: pb_base/socket_obj/unix.py:370
msgid "Only root may change ownership of a socket."
msgstr ""

#: pb_base/socket_obj/unix.py:373
#, python-format
msgid "Setting ownership of '%(sock)s' to %(uid)d:%(gid)d ..."
msgstr ""

#: pb_base/socket_obj/unix.py:378
#, python-format
msgid "Start listening on socket with a queue size of %d."
msgstr ""

#: pb_base/translate.py:40
#, python-format
msgid "Basedir: %r"
msgstr ""

#: pb_base/translate.py:41
#, python-format
msgid "Found .mo-file: %r"
msgstr ""
