# German translations for profitbricks-python-base package
# German messages for profitbricks-python-base.
# Copyright (C) 2013 THE profitbricks-python-base'S COPYRIGHT HOLDER
# This file is distributed under the same license as the profitbricks-python-base package.
# Frank Brehm <frank.brehm@profitbricks.com>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: profitbricks-python-base 0.3.11\n"
"Report-Msgid-Bugs-To: frank.brehm@profitbricks.com\n"
"POT-Creation-Date: 2013-01-14 17:31+0100\n"
"PO-Revision-Date: 2013-01-14 17:49+0100\n"
"Last-Translator: Frank Brehm <frank.brehm@profitbricks.com>\n"
"Language-Team: German\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: pb_base/app.py:411
msgid "The application is not complete initialized."
msgstr "Die Anwendung wurde noch nicht vollständig initialisiert."

#: pb_base/app.py:422
#, python-format
msgid "Object '%s' seems not to be completely initialized."
msgstr "Das Objekt '%s' scheint noch nicht vollständig initialisiert worden zu sein."

#: pb_base/app.py:433 pb_base/fork_daemon.py:355
msgid "Ending."
msgstr "Beenden."

#: pb_base/app.py:452
msgid "executing post_run() ..."
msgstr "führe post_run(() aus ..."

#: pb_base/app.py:474
msgid "General options"
msgstr "Allgemeine Optionen"

#: pb_base/app.py:483
msgid "Use colored output for messages."
msgstr "Verwende farbige Ausgabe für Meldungen."

#: pb_base/app.py:489
msgid "Increase the verbosity level"
msgstr "Erhöhen des Ausführlichkeits-Niveaus."

#: pb_base/app.py:495
msgid "Show this help message and exit"
msgstr "Zeigt die Hilfe-Meldung an und beendet sich."

#: pb_base/app.py:501
msgid "Display brief usage message and exit"
msgstr "Stellt eine kurze Meldung zur Verwendung dar und beendet sich."

#: pb_base/app.py:506
#, python-format
msgid "Version of %(prog)s: %s"
msgstr "Programmversion von %%(prog)s: %s"

#: pb_base/app.py:507
msgid "Show program's version number and exit"
msgstr "Stellt die Programmversion dar und beendet sich."

#: pb_base/cfg_app.py:313
msgid ""
"Configuration file to use additional to the standard configuration files."
msgstr ""
"Konfigurationsdatei, die zusätzlich zu den Standard-Konfigurations-Dateien "
"verwendet werden soll"

#: pb_base/cfg_app.py:322
msgid "The encoding character set of the configuration files"
msgstr "Der Encoding-Zeichensatz der Konfigurations-Dateien"

#: pb_base/cfg_app.py:330
msgid ""
"Generates a default configuration, prints it out to STDOUT and exit"
msgstr ""
"Generiert eine Standard-Konfiguration, schreibt diese nach STDOUT "
"und beendet sich."

#: pb_base/cfg_app.py:433
#, python-format
msgid "Read cfg files with character set '%s' ..."
msgstr "Lese Konfigurations-Dateien mit Zeichensatz '%s' ..."

#: pb_base/cfg_app.py:451
msgid "Used config specification:"
msgstr "Verwendete Konfigurations-Beschreibung:"

#: pb_base/cfg_app.py:460
#, python-format
msgid "Reading in configuration file '%s' ..."
msgstr "Lese Konfigurations-Datei '%s' ein ..."

#: pb_base/cfg_app.py:471
msgid "Found configuration:"
msgstr "Gefundene Konfiguration:"

#: pb_base/cfg_app.py:476
msgid "Validation result:"
msgstr "Ergebnis der Validierung:"

#: pb_base/cfg_app.py:480
#, python-format
msgid "Wrong configuration in '%s' found:"
msgstr "Ungültige Konfigurationsanweisung in '%s' gefunden:"

#: pb_base/cfg_app.py:482
msgid "Configuration error"
msgstr "Konfigurationsfehler"

#: pb_base/cfg_app.py:492
msgid "Using merged configuration:"
msgstr "Verwende fusionierte Konfiguration:"

#: pb_base/cfg_app.py:495
msgid "Using configuration:"
msgstr "Verwende Konfiguration:"

#: pb_base/cfg_app.py:515
msgid "Undefined error"
msgstr "Undefinierter Fehler"

#: pb_base/cfg_app.py:537
#, python-format
msgid "In section %(section)s key '%(key)s': %(value)s"
msgstr "In Abschnitt %(section)s Schlüssel '%(key)s': %(value)s"

#: pb_base/daemon.py:169
#, python-format
msgid "Invalid facility name '%s' given."
msgstr "Ungültiger Facility-Name '%s' angegeben."

#: pb_base/daemon.py:405
#, python-format
msgid "The syslog facility to use when logging as a daemon (default: %s)."
msgstr ""
"Die zu verwendende Syslog-Facility, wenn die Anwendung als Daemon laufen "
"soll (Default: %s)."

#: pb_base/daemon.py:415
msgid ""
"Log to console instead to syslog. Don't daemonize the application, "
"running in foreground."
msgstr ""
"Logging zur Konsole anstatt nach Syslog. Die Anwendung soll im Verdergrund"
"anstelle als eines Daemons laufen."

#: pb_base/daemon.py:524
#, python-format
msgid "Got a signal %s."
msgstr "Signal %s empfangen."

#: pb_base/daemon.py:526
#, python-format
msgid "Process with PID %(pid)d got signal %(signal)s."
msgstr "Der Prozess mit der PID %(pid)d hat das Signal %(signal)s empfangen."

#: pb_base/daemon.py:531
msgid "Nothing to do on signal USR1 or USR2."
msgstr "Auf das Signal USR1 oder USR2 brauch ich nichts zu tun."

#: pb_base/daemon.py:539
msgid "Got a signal for forced shutdown."
msgstr "Habe ein Signal zum forcierten Herunterfahren empfangen."

#: pb_base/daemon.py:561
#, python-format
msgid "Exit from %s, so sad ..."
msgstr "Beende %s, schade auch ..."

#: pb_base/daemon.py:578
#, python-format
msgid "Using '%s' as error log file."
msgstr "Verwende '%s' als Fehler-Logdatei."

#: pb_base/daemon.py:581
#, python-format
msgid "Using '%s' as parent directory of error log file."
msgstr "Verwende '%s' als übergeordnetes Verzeichnis der Fehler-Logdatei."

#: pb_base/daemon.py:585
#, python-format
msgid "Log directory '%s' doesn't exists."
msgstr "Das Log-Verzeichnis '%s' existiert nicht."

#: pb_base/daemon.py:589
#, python-format
msgid "Log directory '%s' exists, but is not a directory."
msgstr "Das Log-Verzeichnis '%s' existiert, ist aber kein Verzeichnis."

#: pb_base/daemon.py:597
#, python-format
msgid "Could not open error logfile: %s"
msgstr "Konnte Fehler-Logdatei nicht öffnen: %s"

#: pb_base/daemon.py:601
#, python-format
msgid "Could not open error logfile %(log)s: %(err)s"
msgstr "Konnte Fehler-Logdatei %(log)s nicht öffnen: %(err)s"

#. do the first fork
#: pb_base/daemon.py:607
msgid "First fork ..."
msgstr "Erster Fork ..."

#: pb_base/daemon.py:614
msgid "Fork #1 failed: "
msgstr "Fork Nr. 1 fehlgeschlagen: "

#. do second fork
#: pb_base/daemon.py:623
msgid "Second fork ..."
msgstr "Zweiter Fork ..."

#: pb_base/daemon.py:630
msgid "Fork #2 failed: "
msgstr "Fork Nr. 2 fehlgeschlagen: "

#: pb_base/daemon.py:633
#, python-format
msgid "%(app)s (v%(ver)s) started as daemon with PID %(pid)d."
msgstr "%(app)s (v%(ver)s) als Daemon mit der PID %(pid)d gestartet."

#. redirect standard file descriptors
#: pb_base/daemon.py:639
msgid "Redirect standard file descriptors ..."
msgstr "Leite Standard-Dateideskriptoren um ..."

#: pb_base/daemon.py:651
msgid "I'm a daemon now - Boooaaaahhh!!!"
msgstr "Ich bin dämonisiert worden, wau - ·▷▶◊◀◁·"

#: pb_base/errors.py:52
#, python-format
msgid "Function %(func)s() has to be overridden in class '%(cls)s'."
msgstr ""

#: pb_base/errors.py:83
#, python-format
msgid " (timeout after %0.1f secs)"
msgstr ""

#: pb_base/errors.py:109
msgid "Timeout error on reading"
msgstr ""

#: pb_base/errors.py:130
msgid "Timeout error on writing"
msgstr ""

#: pb_base/fork_daemon.py:248
#, python-format
msgid "Wrong value for max_children %(val)d, must be between "
msgstr ""

#: pb_base/fork_daemon.py:269
#, python-format
msgid "Wrong value for timeout_collect_children %d, "
msgstr ""

#: pb_base/fork_daemon.py:358
#, python-format
msgid "Daemon (v%s) ended."
msgstr ""

#: pb_base/fork_daemon.py:385
msgid "Collecting all child processes ..."
msgstr ""

#: pb_base/fork_daemon.py:388
msgid "Collecting finished child processes ..."
msgstr ""

#: pb_base/fork_daemon.py:392
msgid "No active children found."
msgstr ""

#: pb_base/fork_daemon.py:424
#, python-format
msgid "Sending signal %d to all child processes."
msgstr ""

#: pb_base/fork_daemon.py:434
#, python-format
msgid "Maximum timeout of %d seconds for waiting "
msgstr ""

#: pb_base/fork_daemon.py:490
#, python-format
msgid "Removing child %d from active child list ..."
msgstr ""

#: pb_base/fork_daemon.py:513
msgid "Forking a child process ..."
msgstr ""

#: pb_base/fork_daemon.py:531
#, python-format
msgid "Forked with process ID %d."
msgstr ""

#: pb_base/fork_daemon.py:538
msgid "And here is the child ..."
msgstr ""

#: pb_base/handler/__init__.py:68
msgid "Unknown OS command."
msgstr ""

#: pb_base/handler/__init__.py:75
msgid "Empty command list given."
msgstr ""

#: pb_base/handler/df.py:394
#, python-format
msgid "Checking existence of %r ..."
msgstr ""

#: pb_base/handler/df.py:396
#, python-format
msgid "Filesystem object %r doesn't exists."
msgstr ""

#: pb_base/handler/df.py:400
#, python-format
msgid "%r is not given as an absolute path."
msgstr ""

#: pb_base/handler/df.py:405
#, python-format
msgid ""
"Calling 'df' for the following objects:\n"
"%r"
msgstr ""

#: pb_base/handler/df.py:408
msgid "Calling 'df' for real all filesystems."
msgstr ""

#: pb_base/handler/df.py:410
msgid "Calling 'df' for local filesystems."
msgstr ""

#: pb_base/handler/df.py:412
msgid "Calling 'df' for all filesystems."
msgstr ""

#: pb_base/handler/df.py:446 pb_base/handler/fuser.py:182
msgid "undefined error"
msgstr ""

#: pb_base/handler/df.py:451
#, python-format
msgid "Error %d on getting free space of %r: %s"
msgstr ""

#: pb_base/handler/df.py:457
#, python-format
msgid "Didn't found any usable information in output of %r: %r"
msgstr ""

#: pb_base/handler/df.py:469
#, python-format
msgid "Could not evaluate line %(line)r in output of command %(cmd)r."
msgstr ""

#: pb_base/handler/fuser.py:158
#, python-format
msgid "Filesystem object %r doesn't seems to exist. "
msgstr ""

#: pb_base/handler/fuser.py:161
#, python-format
msgid "Filesystem object %r doesn't seems to exist."
msgstr ""

#: pb_base/handler/fuser.py:187
#, python-format
msgid "Error %d on getting fuser information of %r: %s"
msgstr ""

#: pb_base/handler/fuser.py:201
#, python-format
msgid "%r is not an integer value usable as PID."
msgstr ""

#: pb_base/pidfile.py:64
#, python-format
msgid "Invalid pidfile '%(pidfile)s' given: %(reason)s"
msgstr ""

#: pb_base/pidfile.py:67
#, python-format
msgid "Invalid pidfile '%s' given."
msgstr ""

#: pb_base/pidfile.py:96
#, python-format
msgid "The pidfile '%(pidfile)s is currently in use by the "
msgstr ""

#: pb_base/pidfile.py:171
msgid "No filename given on initializing PidFile object."
msgstr ""

#: pb_base/pidfile.py:265
#, python-format
msgid "Pidfile '%s' doesn't exists, not removing."
msgstr ""

#: pb_base/pidfile.py:271
#, python-format
msgid "Auto removing disabled, don't deleting '%s'."
msgstr ""

#: pb_base/pidfile.py:276
#, python-format
msgid "Removing pidfile '%s' ..."
msgstr ""

#: pb_base/pidfile.py:279 pb_base/pidfile.py:314
msgid "Just kidding .."
msgstr ""

#: pb_base/pidfile.py:284
#, python-format
msgid "Could not delete pidfile '%s': %s"
msgstr ""

#: pb_base/pidfile.py:303 pb_base/pidfile.py:369
#, python-format
msgid "Invalid PID %(pid)d for creating pidfile "
msgstr ""

#: pb_base/pidfile.py:312
#, python-format
msgid "Deleting pidfile '%s' ..."
msgstr ""

#: pb_base/pidfile.py:322
#, python-format
msgid "Trying opening '%s' exclusive ..."
msgstr ""

#: pb_base/pidfile.py:325 pb_base/pidfile.py:380
#, python-format
msgid "Simulation mode - don't real writing in '%s'."
msgstr ""

#: pb_base/pidfile.py:335
#, python-format
msgid "Error on creating pidfile '%(pidfile)s': %(err)s"
msgstr ""

#: pb_base/pidfile.py:340 pb_base/pidfile.py:393
#, python-format
msgid "Writing %(pid)d into '%(pidfile)s' ..."
msgstr ""

#: pb_base/pidfile.py:363
msgid "Calling recreate() on a note opened pidfile."
msgstr ""

#: pb_base/pidfile.py:377
#, python-format
msgid "Trying opening '%s' for recreate ..."
msgstr ""

#: pb_base/pidfile.py:388
#, python-format
msgid "Error on recreating pidfile '%(pidfile)s': %(err)s"
msgstr ""

#: pb_base/pidfile.py:424
#, python-format
msgid "Pidfile parent directory '%s' doesn't exists."
msgstr ""

#: pb_base/pidfile.py:428
#, python-format
msgid "Pidfile parent directory '%s' is not a directory."
msgstr ""

#: pb_base/pidfile.py:432
#, python-format
msgid "No write access to pidfile parent directory '%s'."
msgstr ""

#: pb_base/pidfile.py:439
msgid "It is not a regular file."
msgstr ""

#: pb_base/pidfile.py:456
#, python-format
msgid "Reading content of pidfile %r ..."
msgstr ""

#: pb_base/pidfile.py:481
msgid "No useful information found in pidfile "
msgstr ""

#: pb_base/pidfile.py:487
#, python-format
msgid "Trying check for process with PID %d ..."
msgstr ""

#: pb_base/pidfile.py:494
#, python-format
msgid "Process with PID %d anonymous died."
msgstr ""

#: pb_base/pidfile.py:497
#, python-format
msgid "No permission to signal the process %d ..."
msgstr ""

#: pb_base/pidfile.py:500
#, python-format
msgid "Unknown error: '%s'."
msgstr ""

#: pb_base/pidfile_app.py:297
#, python-format
msgid "The name of the pidfile (Default: %s)."
msgstr ""

#: pb_base/pidfile_app.py:312
msgid "Simulation mode, nothing is really done."
msgstr ""

#: pb_base/pidfile_app.py:353
#, python-format
msgid "Creating pidfile '%s' ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:73
msgid "Timeout error on reading from socket"
msgstr ""

#: pb_base/socket_obj/__init__.py:92
msgid "Timeout error on writing to socket"
msgstr ""

#: pb_base/socket_obj/__init__.py:161
#, python-format
msgid "Invalid request_queue_size %r, must be "
msgstr ""

#: pb_base/socket_obj/__init__.py:171
#, python-format
msgid "Invalid buffer size %(bs)r, must be "
msgstr ""

#: pb_base/socket_obj/__init__.py:330
msgid "Closing socket ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:340
msgid "Resetting connection ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:359 pb_base/socket_obj/__init__.py:370
msgid "Cannot send message to the receipient, because "
msgstr ""

#: pb_base/socket_obj/__init__.py:375
#, python-format
msgid "Sending %r to socket."
msgstr ""

#: pb_base/socket_obj/__init__.py:390
msgid "Cannot accept connection, socket is not bonded."
msgstr ""

#: pb_base/socket_obj/__init__.py:398
#, python-format
msgid "Got a request from '%s'."
msgstr ""

#: pb_base/socket_obj/__init__.py:400
msgid "Got a request from somewhere from system."
msgstr ""

#: pb_base/socket_obj/__init__.py:421
msgid "Trying to get data ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:430
#, python-format
msgid "Got data: %r."
msgstr ""

#: pb_base/socket_obj/__init__.py:435
msgid "Got EOF, counterpart has interrupted ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:486
msgid "Performing input buffer ..."
msgstr ""

#: pb_base/socket_obj/__init__.py:490
#, python-format
msgid "Current input buffer: %r"
msgstr ""

#: pb_base/socket_obj/__init__.py:496
#, python-format
msgid "Got a line: %r"
msgstr ""

#: pb_base/socket_obj/__init__.py:497
#, python-format
msgid "Current input buffer after read_line(): %r"
msgstr ""

#: pb_base/socket_obj/unix.py:59
#, python-format
msgid "The Unix socket file '%s' was not found."
msgstr ""

#: pb_base/socket_obj/unix.py:70
#, python-format
msgid "Invalid permissions to connect to Unix socket '%s'."
msgstr ""

#: pb_base/socket_obj/unix.py:239
#, python-format
msgid "Removing socket '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:247
#, python-format
msgid "Connecting to Unix Domain Socket '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:251 pb_base/socket_obj/unix.py:282
#, python-format
msgid "The socket is even connected to '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:255 pb_base/socket_obj/unix.py:286
#, python-format
msgid "The application is allready bonded to '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:266
#, python-format
msgid "Error connecting to Unix Socket '%(sock)s': %(err)s"
msgstr ""

#: pb_base/socket_obj/unix.py:278
#, python-format
msgid "Creating and binding to Unix Domain Socket '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:303
#, python-format
msgid "Setting permissions of '%(sock)s' to 0%(perm)o."
msgstr ""

#: pb_base/socket_obj/unix.py:316
#, python-format
msgid "Invalid owner name '%s' for socket creation "
msgstr ""

#: pb_base/socket_obj/unix.py:328
#, python-format
msgid "Invalid group name '%s' for socket creation "
msgstr ""

#: pb_base/socket_obj/unix.py:348
msgid "Only root may change ownership of a socket."
msgstr ""

#: pb_base/socket_obj/unix.py:351
#, python-format
msgid "Setting ownership of '%(sock)s' to "
msgstr ""

#: pb_base/socket_obj/unix.py:357
#, python-format
msgid "Start listening on socket with a queue size of %d."
msgstr ""

#: pb_base/translate.py:40
#, python-format
msgid "Basedir: %r"
msgstr "Basis-Verzeichnis: %r"

#: pb_base/translate.py:41
#, python-format
msgid "Found .mo-file: %r"
msgstr "Gefundene .mo-Datei: %r"

